{
 "title": "Gin Application Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(gin_request_total, app_kubernetes_io_name)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(gin_request_total{app_kubernetes_io_name=~\"$application\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Current PV Rate",
   "type": "gauge",
   "description": "Application request rate every 5 minutes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum  by (application) (rate(gin_request_total{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "PV",
   "type": "graph",
   "description": "Total Page Views",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_instance) (delta(gin_request_total{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\" ,instance=~\"$instance\"}[$__range]))",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "UV",
   "type": "graph",
   "description": "Total Unique Visitors",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_instance) (delta(gin_request_uv_total{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\" ,instance=~\"$instance\"}[$__range]))",
     "legendFormat": "{{app_kubernetes_io_name}}"
    }
   ]
  },
  {
   "title": "URI Request",
   "type": "bargauge",
   "description": "Total requests by URI",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri, app_kubernetes_io_instance) (delta(gin_uri_request_total{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Traffic In-Out",
   "type": "graph",
   "description": "Traffic rate, 5 min rate",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (app_kubernetes_io_instance) (rate(gin_request_body_total{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\" ,instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{app_kubernetes_io_instance}}-in"
    },
    {
     "expr": "sum by (app_kubernetes_io_instance) (rate(gin_response_body_total{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\" ,instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{app_kubernetes_io_instance}}-out"
    }
   ]
  },
  {
   "title": "Method",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(method, app_kubernetes_io_instance) (delta(gin_uri_request_total{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{method}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum (rate(gin_request_duration_bucket{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\",instance=~\"$instance\"}[$__rate_interval])) by (le, app_kubernetes_io_instance))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum (rate(gin_request_duration_bucket{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\",instance=~\"$instance\"}[$__rate_interval])) by (le, app_kubernetes_io_instance))",
     "legendFormat": "p99"
    },
    {
     "expr": "sum (gin_request_duration_sum{job=\"kubernetes-service-endpoints\", app_kubernetes_io_name=~\"$application\",instance=~\"$instance\"}) / sum(gin_request_duration_count{job=\"kubernetes-service-endpoints\", app_kubernetes_io_name=~\"$application\",instance=~\"$instance\"})",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by(code, app_kubernetes_io_instance) (delta(gin_uri_request_total{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "{{app_kubernetes_io_instance}}-{{code}}"
    }
   ]
  },
  {
   "title": "Requests histogram",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 21 },
   "targets": [
    {
     "expr": "sum(increase(gin_request_duration_bucket{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\",instance=~\"$instance\"}[$__interval])/5) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Slow Request(default 5s)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(uri, app_kubernetes_io_name) (gin_slow_request_total{job=\"kubernetes-pods\", app_kubernetes_io_name=~\"$application\",instance=~\"$instance\"})",
     "legendFormat": "{{app_kubernetes_io_name}}-{{uri}}"
    }
   ]
  }
 ]
}