---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: default

#---
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: prometheus-privileged-psp
#subjects:
#  - kind: ServiceAccount
#    name: prometheus
#    namespace: default
#roleRef:
#  kind: ClusterRole
#  name: privileged-psp-user
#  apiGroup: rbac.authorization.k8s.io
#
#---
#kind: ClusterRoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: prometheus-external
#subjects:
#  - kind: ServiceAccount
#    name: prometheus
#    namespace: default
#roleRef:
#  kind: ClusterRole
#  name: prometheus-external
#  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
      - namespaces
      - secrets
      - configmaps
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - pods
      - secrets
      - services
      - configmaps
      - endpoints
    verbs: ["create", "update", "delete"]
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - prometheusrules
      - thanosrulers
      - servicemonitors
      - podmonitors
      - prometheuses
      - alertmanagerconfigs
      - alertmanagers
      - probes
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
    verbs: ["get", "list", "create", "update", "delete"]
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: default
